export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST"
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE"

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_FAILURE = "GET_TODO_FAILURE"

export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS"
export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST"
export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE"


export const GETINDI_TODO_SUCCESS = "GETINDI_TODO_SUCCESS"